version: '2'

services:
  nasa-images:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      PORT: 8000
